default: &default
  adapter: postgresql

development:
  <<: *default
  database: twitter_development

test:
  <<: *default
  database: twitter_test

production:
  <<: *default
  database: twitter_production
  username: twitter
  password: <%= ENV['TWITTER_DATABASE_PASSWORD'] %>
